name: Auto merge into main

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - '**'

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up git
      - name: Merge into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          git checkout main
          git merge ${{ github.ref_name }} --allow-unrelated-histories
          git push origin main
          git fetch origin main
          git checkout main
          git merge ${GITHUB_REF#refs/heads/} --allow-unrelated-histories
          git push origin main
          

  